- name: Ensure ldap tools installed
  package: name=ldap-utils state=present
  become: yes
  tags: test_ad

- name: Test AD Authentication
  command: ldapwhoami -H '{% if item.enable_tls %}ldaps{% else %}ldap{% endif %}://{{ item.hostname }}' -D '{{ item.username }}' -w '{{ item.password }}'
  changed_when: no
  register: ldap_result
  failed_when: ldap_result.rc != 0
  with_items: "{{ ssp_idp_authsources }}"
  tags: test_ad

- name: Generate certs for each auth source
  command: openssl req -newkey rsa:{{ item.ssl_bits }} -new -x509 -days {{ item.ssl_days }} -nodes -out {{ item.domain }}.crt -keyout {{ item.domain }}.pem -subj '{{ item.ssl_subj }}'
  args:
    chdir: "{{ ssp_dir }}/cert"
    creates: "{{ item.domain }}.pem"
  with_items: "{{ ssp_idp_configs }}"
  become_user: "{{ ssp_www_user }}"
  become: yes

- name: Populate ldap.conf
  template: src=ldap.conf.j2 dest=/etc/ldap/ldap.conf
  become: yes
  tags: config

- name: Populate SSP config
  template: src=ssp_config.php.j2 dest="{{ ssp_dir }}/config/config.php"
  become_user: "{{ ssp_www_user }}"
  become: yes
  tags: config

- name: Populate SSP authsources.php
  template: src=authsources.php.j2 dest="{{ ssp_dir }}/config/authsources.php"
  become_user: "{{ ssp_www_user }}"
  become: yes
  tags: config

- name: Populate idp metadata file
  template:
    src="{{ item }}.j2"
    dest="{{ ssp_dir }}/metadata/{{ item }}"
  become_user: "{{ ssp_www_user }}"
  become: yes
  with_items:
    - saml20-idp-hosted.php
  tags: config

- name: Populate sp metadata file
  template:
    src="{{ item }}.j2"
    dest="{{ ssp_dir }}/metadata/{{ item }}"
  become_user: "{{ ssp_www_user }}"
  become: yes
  when: not ssp_cron_enable
  with_items:
    - saml20-sp-remote.php
  tags: config

- name: Setup Certbot
  include: tasks/certbot.yml
  become: yes

- name: Setup SSP Apache
  include: tasks/setup_apache.yml

- name: Populate metadata refresh
  template:
    src=config-metarefresh.php.j2
    dest="{{ ssp_dir }}/config/config-metarefresh.php"
  become_user: "{{ ssp_www_user }}"
  become: yes
  when: ssp_cron_enable
  tags: config

- name: Remove metadata refresh
  file:
    path="{{ ssp_dir }}/config/config-metarefresh.php"
    state=absent
  become_user: "{{ ssp_www_user }}"
  become: yes
  when: not ssp_cron_enable
  tags: config

- name: Force SSP update
  get_url: url='http://{{ ssp_domain }}/simplesaml/module.php/cron/cron.php?key=secret&tag=hourly' dest="/dev/null" force=yes
  become_user: "{{ ssp_www_user }}"
  become: yes
  when: ssp_cron_enable
  tags:
    - update_ssp
